### ISSUE TITLE
Move dependencies from Gemfile to .gemspec

### ISSUE THREAD

**Issue by jorin-vogel** [pocket-playlab/optimus-prime#88]
If we specify all dependencies in the .gemspec already
we can just load them in the Gemfile instead of duplicating them.

**Comment by omarkhan** [comment]
I'm ok with that. Can you submit a PR?

**Comment by jorin-vogel** [comment]
Sorry, I didn't see that the required gems are actually already loaded from the .gemspec file.
https://github.com/pocket-playlab/optimus-prime/blob/master/Gemfile#L5
