### ISSUE TITLE
Remove Legacy Branches

### ISSUE THREAD

**Issue by jorin-vogel** [pocket-playlab/optimus-prime#89]
We should remove all the already merged branches to make it possible to find the ones being active.

**Comment by TamerShlash** [comment]
:+1: thanks for the reminder, I just removed mine.

**Comment by T-Dnzt** [comment]
:+1: Cleaned up mine too.

**Comment by simonbnrd** [comment]
Also removed mine (fix-ruby_version)

**Comment by jorin-vogel** [comment]
Guess, we don't really need an issue for this ...
