### ISSUE TITLE
Variable Pipelines to reuse them if they don't differ much.

### ISSUE THREAD

**Issue by jorin-vogel** [pocket-playlab/optimus-prime#99]
I have four pipelines that work completely the same, only that they have two values that differ from pipeline to pipeline.
Would be nice to set them somehow while running the script. 
Could use ENV variables but that's not how they're supposted to be used I guess..

**Comment by jorin-vogel** [comment]
I solved my problem by building four pipelines in the same file dynamically.
The current setup is flexible enough for me.

Should we still keep this issue @TamerShlash, @T-Dnzt?

**Comment by TamerShlash** [comment]
@jorin-vogel yes I think we don't need it anymore.
